# Configuração TMUX

# source novos atalhos e comandos
source ~/.tmux.conf.behavior
source ~/.tmux.conf.visual

# melhora o uso de cores do terminal
set -g default-terminal "screen-256color"

set-option -g allow-rename off
